### ISSUE TITLE
Congratulations on the creation of this project and repository.

### ISSUE THREAD

**Issue by sam-m888** [HREferg/HRE-the-history-of-everything#1]
Welcome to Github 🥇 

May the projects commits be bountiful and features abundant.

Cheers
Sam

PS: Whats with the name ( HRE-the-history-of-everything ) I was under the impression **HRE** stood for "**[History Research Environment](https://historyresearchenvironment.org/)**" with the slogan "Towards the history of almost everything"  or is this a non official repository and the real one is over here:

 * https://github.com/History-Research-Environment

Which is a proper [Organizational account](https://help.github.com/articles/what-s-the-difference-between-user-and-organization-accounts/) as opposed to [HREferg](https://github.com/HREferg) which is personal?

**Comment by HREferg** [comment]
Hi Sam,

Yes, we’re finally public and I’m loading spec documents – about a 100 more to go.

 

Yes, this is the real repository – have no idea what the other one is

 

Don

**Comment by HREferg** [comment]
Actually Sam I don't know who/how the Organisation repo was created - nor do I know how to find out - any ideas?

Don

**Comment by sam-m888** [comment]
I've been contacted off site by the owner of 

 https://github.com/History-Research-Environment

who has now added me as as part of it, I'll send an invite for you to join the organization.

Then you can transfer the repository to the organization

Transferring a repository to another user account or to an organization

* On GitHub, navigate to the main page of the repository.

* Repository settings buttonUnder your repository name, click  Settings.

* Click Transfer.

* Read the warnings and enter the repository name to confirm that you've done so.

* Type the name of the new owner ( History-Research-Environment ) and click I understand, transfer this repo.

**Comment by HREferg** [comment]
Thanks Sam - closing this issue too

**Comment by sam-m888** [comment]
Your welcome.

**Comment by HREferg** [comment]
So how did you find Johnathon? Who is he? We’d like to thank him for releasing this back to us too!

 

Don

**Comment by ghost** [comment]
> So how did you find Johnathon? Who is he? We’d like to thank him for releasing this back to us too!

I'm a long time TMG user since 1998 !!

Thanks for the thanks but no need really, set this up a while ago with the intention of emailing the HRE website, but life...!

@HREferg Found this project via the announcement on the [reddit for HRE](https://www.reddit.com/r/historyresearcheviro/)  then saw this issue from @sam-m888 and contacted him via the email listed on his profile (did look at your profile but no email listed)

**Comment by HREferg** [comment]
Well, many thanks Johnathon – we were afraid we had a troll sitting on the Org waiting for his $10,000 reward !!

 

What’s your background? Have any coding experience in Java? We really need some!

 

Don Ferguson

**Comment by ghost** [comment]
> Well, many thanks Johnathon – we were afraid we had a troll sitting on the Org waiting for his $10,000 reward !! 

No problem, really need to stop those trolls! 👍 

> What’s your background? 

Work in the finance industry.   How about yourself?

> Have any coding experience in Java? 

C/C++  mostly and can get by in Java.

> We really need some!

Ah.. the perennial problem of all open source projects,  will try my best as I would love to see a modern version of TMG

Good to see HRE has specification documentation, planning always makes things easier 🥇

**Comment by HREferg** [comment]
Well I’m semi-retired, background in IT (as has much of the HRE Board), coding skills are very rusty in 3rd-gen products and Assembler on REAL computers.

Have been dabbling in Java but find it totally frustrating….

 

There are about another 100 spec documents to load (we’ve been working on the design for a couple of years so far, but just HAD to get something down on paper!)
