### ISSUE TITLE
This is only a suggestion of support for other database backends

### ISSUE THREAD

**Issue by StoltHD** [HREferg/HRE-the-history-of-everything#75]
You should really look at database types for linked data, like neo4j or document based that support linked data like mongodb...

Or any similar types of databases...

graph databases will give you huge benefits over a relation database, all the data in a project like this will be some kind of linked data...

Just a suggestion... I'm looking forward and hope that I will be able to use this system to see if it fits my research.

**Comment by HREferg** [comment]
Thank you for your input on this critical matter of database choice. We have reviewed your suggestions but will not, at this stage, be making any changes in the current HRE database choice. There are a number of reasons for this, the chief ones being:

*	The HRE software platform was decided some time ago and a change in direction at this stage of development would have a negative impact on the development process
*	The suggested database types do not conform to the HRE requirement for the code base to be free and Open Source
*	There is a requirement for some degree of compatibility with TMG to allow the initial transfer of TMG data to a structure which can then be extended
*	There are potential issues relating to the continuance and ongoing support of any non-SQL databases, such as those suggested.

 

If, as you suggest, there is value in the use of graphical databases (and this may be true for some components of historical research processes) then no doubt a developer could embody this in an HRE plugin at some time in the future.

 

Don Ferguson

Secretary, HRE Ltd

 

From: StoltHD ***@***.***> 
Sent: Thursday, 29 July 2021 11:25 PM
To: History-Research-Environment/HRE--History-Research-Environment ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [History-Research-Environment/HRE--History-Research-Environment] This is only a suggestion of support for other database backends (#75)

 

You should really look at database types for linked data, like neo4j or document based that support linked data like mongodb...

Or any similar types of databases...

graph databases will give you huge benefits over a relation database, all the data in a project like this will be some kind of linked data...

Just a suggestion... I'm looking forward and hope that I will be able to use this system to see if it fits my research.

**Comment by StoltHD** [comment]
It would NOT be a problem to import TMG Databases to a graph database.

And you are wrong regarding the "open source" comment, there is multiple graph databases on the marked that is open source and free, most likely one that is compatible with your choice of license variant to.

And the continuance and ongoing support is as secure for any nonSQL datbases as it is for any open source sql databases.
And it is a little strange to bring up this as an argument, when you have chosen a database system where last update was in 2019...?

Most of the open source projects has large companies supporting them.
