### ISSUE TITLE
Location of actual HRE [java source] code?

### ISSUE THREAD

**Issue by wroldwiedbwe** [HREferg/HRE-the-history-of-everything#76]
The repository is labeled "Main repo for HRE code"  but I'm unable to actually find the source code for HRE does another repository exist or am I missing something?

**Comment by ricko2001** [comment]
I've wondered about this for years now.

**Comment by HREferg** [comment]
The rate of change of HRE code is not conducive to use of GitHub as the repository and code was deleted some time ago. After release of the current Build to alpha testers on Oct 15, the source was loaded to GitHub.
